# Generated by Django 3.0.3 on 2020-02-15 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200213_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='place',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('light', 'danger!'), ('light', 'Normal'), ('light', 'Low')], max_length=50),
        ),
    ]
